name: PSScriptAnalyzer
on: [push, pull_request]
jobs:
  lint:
    name: Run PSScriptAnalyzer
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: lint
      uses: alagoutte/github-action-psscriptanalyzer@master
      with:
        sendComment: true
        failOnErrors: true
        failOnWarnings: false
        failOnInfos: false
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        settingsPath: .github/workflows/PSScriptAnalyzerSettings.psd1